openapi: 3.0.0
info:
  title: User data API for grid-wolf
  description: |-
    This API provides endpoints for updating and retrieving user data for grid-wolf.
  version: 0.1.0
paths:
  /player-game/{gameId}:
    options:
      operationId: optionsPlayerGame
      security: []
      parameters: 
        - in: path
          name: gameId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Enable CORS support
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "never"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods: "'*'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
    get:
      description: Retrieve a game to which the authorized user has been invited
      operationId: getPlayerGame
      security: 
        - apiKey: []
        - cognitoPool:
          - openid
      parameters: 
        - in: path
          name: gameId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerGame'
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: arn:aws:apigateway:{{region}}:lambda:path/2015-03-31/functions/{{handler}}/invocations
        httpMethod: POST
        responseParameters:
          method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
          method.response.header.Access-Control-Allow-Methods: "'*'"
          method.response.header.Access-Control-Allow-Origin: "'*'"
  /player-game/{gameId}/{participantAction}:
    options:
      operationId: optionsPlayerGameParticipantAction
      security: []
      parameters: 
        - in: path
          name: gameId
          required: true
          schema:
            type: string
        - in: path
          name: participantAction
          required: true
          schema:
            type: string
            enum:
              - accept
              - decline
      responses:
        '200':
          description: Enable CORS support
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "never"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods: "'*'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
    patch:
      description: Accept or decline an invitation to a specific game
      operationId: patchPlayerGameParticipantAction
      security: 
        - apiKey: []
        - cognitoPool:
          - openid
      parameters: 
        - in: path
          name: gameId
          required: true
          schema:
            type: string
        - in: path
          name: participantAction
          required: true
          schema:
            type: string
            enum:
              - accept
              - decline
      responses:
        '202':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: arn:aws:apigateway:{{region}}:lambda:path/2015-03-31/functions/{{handler}}/invocations
        httpMethod: POST
        responseParameters:
          method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
          method.response.header.Access-Control-Allow-Methods: "'*'"
          method.response.header.Access-Control-Allow-Origin: "'*'"
  /player-game/list:
    options:
      operationId: optionsPlayerGameList
      security: []
      responses:
        '200':
          description: Enable CORS support
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "never"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods: "'*'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
    get:
      description: Retrieve a list of games to which the authorized user has been invited
      operationId: getPlayerGameList
      security: 
        - apiKey: []
        - cognitoPool:
          - openid
      responses:
        '200':
          description: Successful operation
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerGames'
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: arn:aws:apigateway:{{region}}:lambda:path/2015-03-31/functions/{{handler}}/invocations
        httpMethod: POST
        responseParameters:
          method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
          method.response.header.Access-Control-Allow-Methods: "'*'"
          method.response.header.Access-Control-Allow-Origin: "'*'"
components:
  schemas:
    PlayerGame:
      type: object
      required:
        - playerId
        - gameId
        - participationState
        - timestamp
      additionalProperties: false
      properties:
        playerId:
          type: string
        gameId:
          type: string
        participationState:
          type: string
          enum:
            - invited
            - accepted
            - declined
            - removed
        timestamp:
          type: number
    PlayerGames:
      type: array
      items:
        $ref: '#/components/schemas/PlayerGame'
    ApiResponse:
      type: object
      properties:
        statusCode:
          type: integer
        message:
          type: string
  securitySchemes:
    apiKey:
      type: apiKey
      name: x-api-key
      in: header
    cognitoPool:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        identitySource: Authorization
        authorizerResultTtlInSeconds: 300
        providerARNs:
          - {{authArn}}
x-amazon-apigateway-request-validators:
  Validate body:
    validateRequestParameters: false
    validateRequestBody: true
